export const routes = {
  home: "/",
  product: "/product",
  solutions: "/solutions",
  business: "/business",
  howItWorks: "/how-it-works",
  resources: "/resources",
  docs: "/resources/docs",
  guides: "/resources/guides",
  help: "/resources/help",
  blog: "/resources/blog",
  platform: "/platform",
  security: "/security",
  verify: "/verify",
  scan: "/scan",
  getStarted: "/get-started",
  pricing: "/pricing",
  about: "/about",
  login: "/auth/login",
  signup: "/auth/signup",
  dashboard: "/dashboard",
  privacy: "/privacy",
  terms: "/terms",
  risks: "/risks",
  counterfeitInundation: "/risks/counterfeit-inundation",
  lostSupplyChain: "/risks/lost-supply-chain-story",
  unverifiableWarranties: "/risks/unverifiable-warranties",
  delayedRecallAlerts: "/risks/delayed-recall-alerts",
  opaqueProductOrigin: "/risks/opaque-product-origin",
} as const;

export type AppRoute = (typeof routes)[keyof typeof routes];
